pipeline{
    agent{
        docker{image 'node:14'
                args '-u root:sudo'
            }
    }

    stages{
        stage('install-env'){
            
            steps{
                //sh 'sudo chown -R 995:993 "/.npm"'
                sh 'npm install'
            }
            post{
                success{
                    echo "Successful intall npm"
                }
                failure{
                    echo "Fail install nmp"
                }
            }
        }
        stage('package'){
            steps{
                sh 'npm pack'
            }
            post{
                success{
                    echo 'Successful package'
                }
                failure{
                    echo 'fail package'
                }
            }
        }
    }
}
