pipeline{
    agent any

    stages{
        stage('install-env'){
            agent{docker{image 'node'}}
            steps{
                sh 'npm install'
            }
            post{
                success{
                    echo "Successful intall npm"
                }
                failure{
                    echo "Fail install nmp"
                }
            }
        }
    }
}
